### ISSUE TITLE
train.yml not found

### ISSUE THREAD

**Issue by kimtaehyeong** [zononhzy/LAMNet#1]
Thank you for your great research!
I currently want to custom train that model with my own dataset.
The 'train.yml' is not provided for training. Where can I find it?

thank you

**Comment by zononhzy** [comment]
Thank you for your interest in my research and for reaching out! 😊
I have just uploaded the training.yml file to the repository. Please feel free to check it out. If you have any further questions or encounter any issues while training with your dataset, don’t hesitate to let me know!

Happy experimenting and best of luck with your custom training! 🚀

**Comment by kimtaehyeong** [comment]
Thank you! The issue has been resolved.
